name: ShutterPvP
main: org.shutterspiny.plugin.ShutterPvP.SGPlugin
version: 0.7
commands:
  sgcreatemap:
    description: Creates a SG map.
    usage: /sgcreatemap <map-name>
    permission: ShutterPvP.maps
  sgmapinfo:
    description: Displays info about a SG map.
    usage: /sgmapinfo <map-name>
    permission: ShutterPvP.maps
  sgeditmap:
    description: Selects a SG map for editing.
    usage: /sgeditmap <map-name>
    permission: ShutterPvP.maps
  sgstopeditting:
    description: Deselects your currently selected SG map.
    usage: /sgstopeditting
    permission: ShutterPvP.maps
  sgaddchest:
    description: Adds a chest as the block you're looking at. Rarity argument represents how hard the chest is to get to.
    usage: /sgaddchest <rarity>
    permission: ShutterPvP.maps
  sgaddspawnpoint:
    description: Adds a spawnpoint where you're standing in.
    usage: /sgspawnpoint
    permission: ShutterPvP.maps
  sgadditem:
    description: Adds a SGItem with a specified damage value range.
    usage: /sgadditem <rarity> <min-count> <max-count> <min-damage> <max-damage>
    permission: ShutterPvP.maps
  sgadditemdamaged:
    description: Adds a SGItem constructed from the item in your hand.
    usage: /sgadditem <rarity> <min-count> <max-count>
    permission: ShutterPvP.maps
  sgenchant:
    description: Unsafe enchanting.
    usage: /sgenchant <enchantment-name> <level>
    permission: ShutterPvP.maps
  sgaddmineable:
    description: Makes the type of block your looking at mineable when playing on the selected map.
    usage: /sgaddmineable
    permission: ShutterPvP.maps
  sgaddplaceable:
    description: Makes the type of block your looking at placeable when playing on the selected map.
    usage: /sgaddplaceable
    permission: ShutterPvP.maps
  sgaddentity:
    description: Adds an entity.
    usage: /sgaddentity <entity-name> <entity-type-name>
    permission: ShutterPvP.maps
  sgaddspawner:
    description: Adds a SGSpawner where you're standing to the currently selected map. Set repeats to -1 to repeat forever.
    usage: /sgaddspawner <entity-name> <delay> <max-entities> <repeats>
    permission: ShutterPvP.maps
  sgsave:
    description: Saves maps.
    usage: /sgsave
    permission: ShutterPvP.maps
  sgload:
    description: Loads maps.
    usage: /sgload
    permission: ShutterPvP.maps
  sglistmaps:
    description: Lists maps.
    usage: /sglistmaps
    permission: ShutterPvP.maps
  sgstart:
    description: Starts the game.
    usage: /sgstart
    permission: ShutterPvP.games
  sgsetmap:
    description: Sets the game's map.
    usage: /sgsetmap <map-name>
    permission: ShutterPvP.games
  sgjoin:
    description: Joins the game.
    usage: /sgjoin
    permission: ShutterPvP.games
  sgstop:
    description: Stops the game.
    usage: /sgstop
    permission: ShutterPvP.games
  sgleave:
    description: Leaves the game.
    usage: /sgleave
    permission: ShutterPvP.games
permissions:
  ShutterPvP.maps:
    desciption: Gives access to all SG map-editing commands. Ops have this permission by default.
    default: op
  ShutterPvP.games:
    desciption: Gives access to all SG game commands. Ops have this permission by default.
    default: op